// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectToRemote(arg1:string):Promise<void>;

export function Copy(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetAppURL():Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetEmbeddedFrontend():Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetServiceStatus():Promise<Record<string, any>>;

export function IsSetupComplete():Promise<boolean>;

export function ListDirectory(arg1:string):Promise<Array<Record<string, any>>>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function SaveConfiguration(arg1:main.Config):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartServices():Promise<void>;

export function StopServices():Promise<void>;

export function ValidatePath(arg1:string):Promise<Record<string, any>>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
