// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToRemote(arg1) {
  return window['go']['main']['App']['ConnectToRemote'](arg1);
}

export function Copy(arg1) {
  return window['go']['main']['App']['Copy'](arg1);
}

export function FileExists(arg1) {
  return window['go']['main']['App']['FileExists'](arg1);
}

export function GetAppURL() {
  return window['go']['main']['App']['GetAppURL']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetEmbeddedFrontend() {
  return window['go']['main']['App']['GetEmbeddedFrontend']();
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetPlatformInfo() {
  return window['go']['main']['App']['GetPlatformInfo']();
}

export function GetServiceStatus() {
  return window['go']['main']['App']['GetServiceStatus']();
}

export function IsSetupComplete() {
  return window['go']['main']['App']['IsSetupComplete']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveConfiguration(arg1) {
  return window['go']['main']['App']['SaveConfiguration'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function StartServices() {
  return window['go']['main']['App']['StartServices']();
}

export function StopServices() {
  return window['go']['main']['App']['StopServices']();
}

export function ValidatePath(arg1) {
  return window['go']['main']['App']['ValidatePath'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
